### PR TITLE
change "personal" to "Starter"

### PR DESCRIPTION
**Pull request by Perefin**
Just want to change the language to clarify “Starter” instead of using the word “personal” - sorry if the etiquette is to discuss first, just figured this is would be appropriate for such a simple change. Happy to follow protocol in the future as necessary.

### CODE REVIEW

**Review by notrab — APPROVED** [review]
Thank you 🙏

**Comment by notrab** [comment]
@Perefin we also have this page that mentions “free users”. Which is clearer to you? Mentioning the free plan by name or using the word free on both of these pages? https://docs.turso.tech/features/scale-to-zero

**Comment by Perefin** [comment]
I would say “free Starter plan” covers all bases and is more clear than
“free personal plan.” We could say “free Starter plan users” on the
scale-to-zero page - wdyt?

**Comment by notrab** [comment]
Sounds good to me! Do you want to make those changes?

**Comment by Perefin** [comment]
Done! I think. Pull request sent for scale-to-zero as well

**Pull request merged**
