### PR TITLE
rename archived to sleeping

### PR DESCRIPTION
**Pull request by notrab**

### CODE REVIEW

**Review by LucioFranco — APPROVED** [review]

**Comment by athoscouto** [comment]
That is not what the API is returning though, is it? @notrab

**Comment by notrab** [comment]
@athoscouto yeah the API returns `sleeping`:

```json
{
    "database": {
        "Name": "myrootschema",
        "DbId": "b8e89975-d722-11ee-a86f-f2e159adf5c7",
        "Hostname": "myrootschema-notrab.turso.io",
        "is_schema": false,
        "schema": "",
        "block_reads": false,
        "block_writes": false,
        "allow_attach": false,
        "type": "logical",
        "hostname": "myrootschema-notrab.turso.io",
        "version": "0.22.22",
        "sleeping": false
    }
}
```

**Comment by athoscouto** [comment]
@notrab but does the group model also have a `sleeping` field? 
We may be talking about different endpoints, but the ones that return a group that I see come with the `archived` field.

**Review by gris — APPROVED** [review]

**Comment by notrab** [comment]
@athoscouto ah, yes. Good catch!

@gris do we want to update the API to return `sleeping` there also?

**Comment by athoscouto** [comment]
@notrab let me get that fixed 🤓

**Comment by notrab** [comment]
I'll close this for now, but we can revisit once we unify the API responses elsewhere.

**Pull request closed without merging**
